"""API response schemas."""

from datetime import datetime, timezone
from typing import Any, Optional

from pydantic import BaseModel, Field


class CarVisualReport(BaseModel):
    """Structured physical condition report generated by BLIP VQA."""

    front: str = Field(..., description="Front view inspection caption")
    rear: str = Field(..., description="Rear view inspection caption")
    side: str = Field(..., description="Side view inspection caption")
    interior: str = Field(..., description="Interior view inspection caption")


class PredictionResponse(BaseModel):
    """Prediction result returned by the API."""

    predicted_price: float = Field(..., description="Predicted resale value in Lakhs (INR)")
    currency: str = Field(default="INR", description="Currency code (INR)")
    confidence_band: Optional[dict[str, float]] = Field(
        None, description="Confidence interval (±10%)"
    )
    vehicle_summary: str = Field(..., description="Human-readable vehicle summary")
    visual_report: CarVisualReport = Field(..., description="Comprehensive BLIP visual inspection report")
    valuation_report: Optional[dict] = Field(
        None, description="LLM-generated structured valuation report"
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


class HealthResponse(BaseModel):
    """Health check response."""

    status: str = Field(..., description="Service status")
    version: str = Field(..., description="Application version")
    model_loaded: bool = Field(..., description="Whether ML model is loaded")


class ErrorResponse(BaseModel):
    """Standardised error response."""

    error: str = Field(..., description="Error message")
    details: Any = Field(None, description="Additional error context")
